### ISSUE TITLE
MacOS Script Install issue

### ISSUE THREAD

**Issue by hiddenbytes** [ydkhatri/mac_apt#82]
Hello,
New Mac user here, so I am hoping it is something obvious.

I am trying to install Mac_apt onto  Big Sur (11.6.5), however the script has given me the following error:

[!] Installation of pyvmdk failed due to an error.
[!] Please report this to the developer.

----

Following the manual instructions, I get this error when trying to install pytsk3 and libvmdk-pytho:

creating build
      creating build/temp.macosx-11-x86_64-3.9
      creating build/temp.macosx-11-x86_64-3.9/libbfio
      creating build/temp.macosx-11-x86_64-3.9/libcdata
      creating build/temp.macosx-11-x86_64-3.9/libcerror
      creating build/temp.macosx-11-x86_64-3.9/libcfile
      creating build/temp.macosx-11-x86_64-3.9/libclocale
      creating build/temp.macosx-11-x86_64-3.9/libcnotify
      creating build/temp.macosx-11-x86_64-3.9/libcpath
      creating build/temp.macosx-11-x86_64-3.9/libcsplit
      creating build/temp.macosx-11-x86_64-3.9/libcthreads
      creating build/temp.macosx-11-x86_64-3.9/libfcache
      creating build/temp.macosx-11-x86_64-3.9/libfdata
      creating build/temp.macosx-11-x86_64-3.9/libfvalue
      creating build/temp.macosx-11-x86_64-3.9/libuna
      creating build/temp.macosx-11-x86_64-3.9/libvmdk
      creating build/temp.macosx-11-x86_64-3.9/pyvmdk

<<Snip>>

le -Ilibcpath -Ilibbfio -Ilibfcache -Ilibfdata -Ilibfvalue -Ilibvmdk -I/Users/macbookpro/Forensic_Tools/mac_apt/env/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c libclocale/libclocale_support.c -o build/temp.macosx-11-x86_64-3.9/libclocale/libclocale_support.o
      libclocale/libclocale_support.c:26:10: fatal error: 'libintl.h' file not found
      #include <libintl.h>
               ^~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> libvmdk-python

I've tried reinstalling and relinking gettext through Brew, as suggested elsewhere online, but I'm still getting the error. 
Is anyone familiar with this issue and is there any workarounds/ solution to this?

Thanks!

**Comment by hiddenbytes** [comment]
This has now been resolved. I ended up reinstalling my mac again, this time using 'US English' and the script now runs/ installs.

Thanks!

**Comment by mailinglists35** [comment]
experiencing this as well. latest release, macOS monterey 12.6.1

**Comment by ozbekburak** [comment]
> experiencing this as well. latest release, macOS monterey 12.6.1

As README indicates: `Note: certain dependencies do not work on Python 3.11 ! So use 3.9 or 3.10 for now.`
